# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-10 23:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='static/media'),
            preserve_default=False,
        ),
    ]
