# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-11 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagina", "0002_presentation_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=b""),
        ),
    ]
