# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-16 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagina", "0005_presentation_is_favorite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="description",
            field=models.TextField(max_length=200),
        ),
    ]
