# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pagina", "0006_auto_20181116_0310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="description",
            field=models.TextField(max_length=500),
        ),
    ]
