# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0007_auto_20181116_2217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='presentation',
            new_name='Heroes',
        ),
    ]
