# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-03 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0008_auto_20190303_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='image',
            field=models.ImageField(default='', upload_to=b''),
        ),
    ]
