# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-05 00:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0010_auto_20190303_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heroes',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='heroes',
            name='image',
            field=models.ImageField(upload_to='%Y-%m-%d/'),
        ),
    ]
